#pragma once
//Screen Dimensions
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MOVEMENTSPEED 70.0f
#define GRAVITY 130.0f
#define JUMP_FORCE_DECREMENT 250.0f
#define INITIAL_JUMP_FORCE 400.0f
#define INITIAL_JUMP_FORCE_SMALL 300.0f
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define SHAKE_DURATION 0.25f
#define INJURED_TIME 3.0f 
#define KOOPA_SPEED 96.0f
#define ANIMATION_DELAY 0.10f